version: "3.8"

services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: khalid
      POSTGRES_PASSWORD: khalid
      POSTGRES_DB: test
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U khalid"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  db_data:
