import type { Metadata } from "next";
import { Nunito } from "next/font/google";
import { PT_Sans } from "next/font/google";
import "./globals.css";
import { Providers } from "@/lib/providers";
import { Toaster } from "sonner";

const nunito = Nunito({
  variable: "--font-nunito",
  subsets: ["latin"],
});

const ptSans = PT_Sans({
  variable: "--font-pt-sans",
  subsets: ["latin"],
  weight: ["400", "700"],
});

export const metadata: Metadata = {
  title: "Drizzle Next App",
  description: "Generated by Drizzle Next",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html suppressHydrationWarning lang="en">
      <body
        className={`${nunito.variable} ${ptSans.variable} antialiased bg-background text-foreground`}
      >
        <Texture enabled={false} />
        <Providers>
          {children}
          <Toaster position="top-right" />
        </Providers>
      </body>
    </html>
  );
}

function Texture({ enabled }: { enabled: boolean }) {
  return (
    <div
      style={{
        backgroundImage: "url('/texture.jpg')",
      }}
      className={`fixed inset-0 w-screen h-[100dvh] opacity-20 mix-blend-multiply z-100 pointer-events-none bg-repeat bg-cover ${
        enabled ? "block" : "hidden"
      }`}
    />
  );
}
